### ISSUE TITLE
Impolite service termination

### ISSUE THREAD

**Issue by jaraco** [pytest-dev/pytest-xprocess#1]
xprocess uses 'terminate' and 'kill' like synonyms, but in practice, uses `.kill()` or `SIGKILL` for terminating processes. Instead, it should use a terminate/wait/kill loop similar to what [pytest.services does](https://github.com/pytest-dev/pytest-services/blob/1.2.1/pytest_services/service.py#L70-L80).

**Comment by jaraco** [comment]
Using SIGKILL without using SIGKILL will leave child processes orphaned.

**Comment by d6e** [comment]
@jaraco In the future, can you please not change the public api for a package? We were depending on this library and this change broke our stuff.  :(

**Comment by nicoddemus** [comment]
Hmm right, that did change the public API but nobody noticed while reviewing it, which is unfortunate.

Perhaps we should reintroduce the old `kill` as an alias for `terminate` (issuing a `DeprecationWarning` perhaps?) and make a new release?

**Comment by nicoddemus** [comment]
Awesome, thanks @jaraco!

**Comment by jaraco** [comment]
0.11.1 released with tested fix for regression.

**Comment by nicoddemus** [comment]
Thanks @jaraco!
