### ISSUE TITLE
Implicit dependency on `py` causes failure of pytest==7.2.0 runs when xprocess is installed

### ISSUE THREAD

**Issue by jclerman** [pytest-dev/pytest-xprocess#110]
**Describe the bug**
Missing dependency on `py` causes failure of pytest==7.2.0 runs when xprocess is installed.

**To Reproduce**
From a clean environment (say using Python 3.9; this issue affects at least python 3.8 and 3.9):
```
% pip install pytest==7.2.0
% pip install pytest-xprocess==0.20.0
% python
>>> import xprocess
```

**Expected behavior**
No error should be raised.

**Actual result**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/***/Library/Caches/pypoetry/virtualenvs/mypackage-l0EsK_Ku-py3.9/lib/python3.9/site-packages/xprocess/__init__.py", line 1, in <module>
    from .xprocess import ProcessStarter
  File "/Users/***/Library/Caches/pypoetry/virtualenvs/mypackage-l0EsK_Ku-py3.9/lib/python3.9/site-packages/xprocess/xprocess.py", line 13, in <module>
    from py import std
ImportError: cannot import name 'std' from 'py' (/Users/***/Library/Caches/pypoetry/virtualenvs/mypackage-l0EsK_Ku-py3.9/lib/python3.9/site-packages/py.py)
>>> from xprocess import ProcessStarter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/***/Library/Caches/pypoetry/virtualenvs/mypackage-l0EsK_Ku-py3.9/lib/python3.9/site-packages/xprocess/__init__.py", line 1, in <module>
    from .xprocess import ProcessStarter
  File "/Users/***/Library/Caches/pypoetry/virtualenvs/mypackage-l0EsK_Ku-py3.9/lib/python3.9/site-packages/xprocess/xprocess.py", line 13, in <module>
    from py import std
ImportError: cannot import name 'std' from 'py' (/Users/***/Library/Caches/pypoetry/virtualenvs/mypackage-l0EsK_Ku-py3.9/lib/python3.9/site-packages/py.py)
```

**Environment:**
 - OS: macOS Monterey
 - Python Version 3.9.13
 - pytest-xprocess version: 0.20.0 (also tested with 0.18.1)

**Additional context**

This problem only occurs with [pytest 7.2.0, which was just released](https://github.com/pytest-dev/pytest/releases/tag/7.2.0).  The issue seems to be that pytest has dropped dependency on the `py` package, which is no longer included when pytest is installed.  `pytest-xprocess` has an implicit dependency on `py` but does not name it as a dependency in `setup.py`, so the import statement in `xprocess.py` fails.

Related `pytest` PR: https://github.com/pytest-dev/pytest/pull/10396

**Comment by The-Compiler** [comment]
Note that, while adding a `py` dependency would be a suitable hotfix (and installing it locally serves as a workaround), the plugin should probably look into dropping reliance on `py` entirely. The library has been in maintenance mode for a while now.

For `std` being used in `xprocess/xprocess.py`, the relevant parts should just be imported directly (`import subprocess` etc.) instead.

For `py.io.TerminalWriter` in `xprocess/pytest_xprocess.py`, perhaps consider doing a private import from pytest instead (`from _pytest._io import TerminalWriter`). While it's not exactly a great solution, it's likely the lesser evil of the two.

**Comment by northernSage** [comment]
I'll go ahead and make a release with the hotfix from #112 for now and look into dropping our dependency on `py` soon, thanks all for the suggestions and letting us know about the issue :bowtie:
