### ISSUE TITLE
ResourceWarning in xprocess.ensure

### ISSUE THREAD

**Issue by davidism** [pytest-dev/pytest-xprocess#119]
Just upgraded to 0.21 from 0.20 for Werkzeug, and am now getting resource warnings from within pytest-xprocess.

```
pytest.PytestUnraisableExceptionWarning: Exception ignored in: <_io.FileIO [closed]>

Traceback (most recent call last):
  File "/home/david/.local/share/virtualenvs/werkzeug/lib/python3.10/site-packages/xprocess/xprocess.py", line 274, in ensure
    lines = info.logpath.open().readlines()
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/david/Projects/pallets/werkzeug/.pytest_cache/d/.xprocess/dev_server-test_streaming_chunked_response/xprocess.log' mode='r' encoding='UTF-8'>
```

The line it's pointing to is this, where a file is opened but not closed. https://github.com/pytest-dev/pytest-xprocess/blob/536344776d4a719ac505f6b8a617e68d1e355e20/xprocess/xprocess.py#L273-L274

**Comment by northernSage** [comment]
Yeah, introduced that with `https://github.com/pytest-dev/pytest-xprocess/pull/105` (oops :bowtie:). I'll release a fix for this along with https://github.com/pytest-dev/pytest-xprocess/pull/118 this weekend. Thanks for the letting me know and sorry about that @davidism
