### ISSUE TITLE
Add child process terminate features.

### ISSUE THREAD

**Issue by GoodManWEN** [pytest-dev/pytest-xprocess#12]
love your work which makes me easily test my socket server.
Here's one problem is that since my server preforks several child process in order to improving handling capacity. Xprocessinfo.terminate only kills the parent but leaves others become zombie process ,So that I have to handle it myself by doing some wired hacking.
Could you please add features that allow process terminate itself and its children at framework level? Thanks.

**Comment by moi90** [comment]
This shouldn't be too hard to implement: https://psutil.readthedocs.io/en/latest/#kill-process-tree

**Comment by northernSage** [comment]
I'm on it, will be submitting a PR soon.
