### ISSUE TITLE
sdist is missing `conftest.py` and `server.py`

### ISSUE THREAD

**Issue by mtelka** [pytest-dev/pytest-xprocess#148]
**Describe the bug**

The sdist package at PyPI is missing `tests/conftest.py` and `tests/server.py`.  Without these files it is not possible to run tests successfuly.

**To Reproduce**
1. Download sdist from PyPI.
2. Unpack it.
3. Run tests.

**Expected behavior**

Testing pass.

**Environment (please complete the following information):**
 - OS: OpenIndiana
 - Python Version 3.9.18
 - pytest-xprocess version 1.0.0

**Comment by northernSage** [comment]
addressed by #149

thanks for the heads up!

**Comment by mgorny** [comment]
Thanks a lot!
