### ISSUE TITLE
Server failed to start

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest-xprocess#16]
I'm trying a quite minimal example with pytest 5.3.4, xprocess 0.12.1 and Python 3.8:

`conftest.py`:

```python
import sys, socket, pytest, py, pathlib
from xprocess import ProcessStarter

@pytest.fixture
def serversock(xprocess):
    port = 5777
    curdir = pathlib.Path(__file__).parent

    class Starter(ProcessStarter):
        pattern = "started"
        args = [sys.executable, curdir / 'server.py', port]

    xprocess.ensure("server-%s" % port, Starter)
    sock = socket.socket()
    sock.connect(("localhost", port))
    return sock
```

`server.py`:

```python
import socketserver
import time
import sys

class MainHandler(socketserver.StreamRequestHandler):
    count = 0
    def handle(self):
        while True:
            line = self.rfile.readline()
            if not line:
                break
            sys.stderr.write("[%d] %r\n" %(self.count, line))
            self.request.sendall(b"1")
            MainHandler.count += 1


class MyServer(socketserver.TCPServer):
    allow_reuse_address = True


if __name__ == "__main__":
    mainserver = MyServer(("localhost", int(sys.argv[1])), MainHandler)
    time.sleep(3) # simulate long startup time
    sys.stderr.write("started\n")
    mainserver.serve_forever()
```

`test_server.py`:

```python
def test_server(serversock):
    serversock.sendall(b'hello\n')
    c = serversock.recv(1)
    assert c == b'1'
```

When I start the server by hand, it runs like expected:

```console
$ python3 server.py 5778                                                                                                                        
started
```

When I try to run xdist, it *also* starts it, but then complains that it couldn't start it:

```
conftest.py:13: in serversock
    xprocess.ensure("server-%s" % port, Starter)
.venv/lib/python3.8/site-packages/xprocess.py:140: in ensure
    raise RuntimeError("Could not start process %s" % name)
E   RuntimeError: Could not start process server-5777
------------------------------------------------------------------------------------ Captured stdout setup ------------------------------------------------------------------------------------
.../.xprocess/server-5777$ .../python3 .../server.py 5777
process 'server-5777' started pid=184070
```

Yet when I run `--xshow` it *is* started:

```
184070 server-5777 LIVE .../.xprocess/server-5777/xprocess.log
```

And when I rerun the tests, they work fine.

What's going wrong? Is my `pattern` wrong in the `ProcessStarter` somehow? The example in the repo only seems to use a `preparefunc` which is deprecated...

**Comment by tsteinholz** [comment]
The pattern has to be regex... so you would really want something like `pattern = "^.*started.*$"`. You can test your regex patterns here: https://regex101.com/

If your regex is getting parsed correctly, I would check to make sure that your "started" message happens in the first 50 lines... It won't read it otherwise! #20

**Comment by The-Compiler** [comment]
The regex is matched with `re.search`, so whether it's `started` or `^.*started.*$` doesn't make any difference:

```
>>> re.search('started', 'my server started successfully')
<re.Match object; span=(10, 17), match='started'>
```

In any case, the pattern `started` definitely matches the string `started`. And in the example above, `started` is the only thing the server prints.

**Comment by pyeres** [comment]
@The-Compiler — try flushing your stderr (`sys.stderr.flush()`) after writing to stderr. E.g.:

> `server.py`:
> 
> ```python
> ...
> if __name__ == "__main__":
>     mainserver = MyServer(("localhost", int(sys.argv[1])), MainHandler)
>     time.sleep(3) # simulate long startup time
>     sys.stderr.write("started\n")
>     sys.stderr.flush()
>     mainserver.serve_forever()
> ```

**Comment by nicoddemus** [comment]
(I didn't look at the code so this is just a wild guess)

Try writing to `stdout` and flushing instead. Not sure how the process is being opened, but `xprocess` might be looking only at `stdout`.

**Comment by pyeres** [comment]
> (I didn't look at the code so this is just a wild guess)
> 
> Try writing to `stdout` and flushing instead. Not sure how the process is being opened, but `xprocess` might be looking only at `stdout`.

[XProcess sends stderr](https://github.com/pytest-dev/pytest-xprocess/blob/3e71f286e06a69af5d4564d33edc4f47e9e8f113/xprocess.py#L119) to [STDOUT](https://docs.python.org/3/library/subprocess.html#subprocess.STDOUT) — writing to `sys.stderr` or `sys.stdout` will work (provided you [`flush`](https://github.com/pytest-dev/pytest-xprocess/blob/3e71f286e06a69af5d4564d33edc4f47e9e8f113/example/server.py#L34)).

**Comment by northernSage** [comment]
The given example is working fine on my end:

pytest==6.1.0
pytest-xprocess==0.14.0 

the only change necessary was adding, as suggested, `sys.stderr.flush()` since stdout is buffered. Other options would be running python with [-u](https://docs.python.org/3/using/cmdline.html#cmdoption-u) options or setting [PYTHONUNBUFFERED](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONUNBUFFERED).

I'm closing the issue for the time being since this doesn't seem to be a problem with `pytest-xprocess`.

**Comment by The-Compiler** [comment]
Sorry for the silence, this got lost in my inbox - indeed adding `sys.stderr.flush()` also fixes things in my larger example. Thanks everyone! :+1:
