### ISSUE TITLE
Fatal error when subprocess has special characters in stdout

### ISSUE THREAD

**Issue by erinpentecost** [pytest-dev/pytest-xprocess#18]
[This line](https://github.com/pytest-dev/pytest-xprocess/blob/master/xprocess.py#L71) throws a `TypeError: not enough arguments for format string` when a started subprocess tries to print a line that python thinks needs argument substitutions. An example is `'      , % /.                            ,@@@.                     %%#    #/%%/ \n'`

**Comment by RonnyPfannschmidt** [comment]
i suspect the bug is in https://github.com/pytest-dev/pytest-xprocess/blob/master/xprocess.py#L202

**Comment by northernSage** [comment]
I'll give this a go.
