### ISSUE TITLE
DOC: How to shutdown the process after the test run

### ISSUE THREAD

**Issue by westurner** [pytest-dev/pytest-xprocess#19]
Is this the correct way to kill the process on scope teardown?

```python
from pathlib import Path
import pytest
from xprocess import ProcessStarter

PATH = Path(__file__) / ".." / "docs"
PORT = 10000

@pytest.fixture(scope='module')
def myserver(xprocess):
    class Starter(ProcessStarter):
        pattern = "^Serving HTTP on"
        args = ["python", "-m", "http.server", "--directory", PATH, PORT]
    logfile = xprocess.ensure("myserver", Starter)  # == logfile
    yield logfile
    xprocess.getinfo("myserver").kill()

def test_name(myserver):
    from urllib.request import urlopen
    resp = urlopen(f"http://localhost:{PORT}")
    assert resp.code == 200
```

http://doc.pytest.org/en/latest/fixture.html#fixture-finalization-executing-teardown-code

This seems to be hanging between subsequent pytest invocations; probably due to open connections?

**Comment by tsteinholz** [comment]
That method never worked for me... but you can use one of the pytest hooks to ensure that your process ends upon test completion...

in your `conftest.py`:
```python
import os
import signal

def pytest_sessionfinish(session, exitstatus):
    proc_name = "myserver"
    with open(f".xprocess/{proc_name}/xprocess.PID") as f:
        pid = int(f.readline().strip())
        os.kill(pid, signal.SIGTERM)  # or signal.SIGKILL
```

**Comment by simonw** [comment]
It would be great if this was a documented feature - I was pretty surprised when I realized that my test servers were left running after `pytest` ended.

Here's the pattern I used to get this working (based on reading the code for the `--xkill` option):
```python
import py
from xprocess import XProcess

def pytest_sessionfinish(session, exitstatus):
    # Shut down all xprocess servers
    tw = py.io.TerminalWriter()
    rootdir = session.config.rootdir.join(".xprocess").ensure(dir=1)
    xprocess = XProcess(session.config, rootdir)
    xprocess._xkill(tw)
```

**Comment by northernSage** [comment]
`XProcessInfo.kill` has been deprecated on [0.11.0](https://github.com/pytest-dev/pytest-xprocess/blob/master/CHANGELOG.rst#011-2017-05-18) and it's currently just an alias for the newer `XProcessInfo.terminate ` which also has seen some changes as of [0.14.0](https://github.com/pytest-dev/pytest-xprocess/blob/master/CHANGELOG.rst#0140-2020-09-24) which specifically address the described issue of lingering processes. Please, check if the lastest release has fixed the problem.

**Comment by westurner** [comment]
Thanks!

**Comment by nrbnlulu** [comment]
This worked for me:
```py
    @pytest.fixture(scope='session', autouse=True)
    def mini_server(self, request) -> MiniServer:
        sock = socket.socket()
        sock.bind(('', 0))
        port = str(sock.getsockname()[1])
        sock.close()
        p = subprocess.Popen(
                args=[
                    'poetry', 'run', 'python', '-m', 'aiohttp.web', '-H', 'localhost',
                    f'-P {port}', 'mini_gql_server:init_func',

                ],
                stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                cwd=Path(__file__).parent
        )
        address = f"ws://localhost:{port}/graphql"
        request.addfinalizer(p.kill)
        yield MiniServer(process=p, address=address, port=port)
```

**Comment by westurner** [comment]
Looks like  just `python -u` or `PYTHONUNBUFFERED=1 python` works with just `.terminate()`

Docs: 
- https://docs.python.org/3/using/cmdline.html#cmdoption-u
- https://docs.python.org/3/using/cmdline.html#envvar-PYTHONUNBUFFERED
