### ISSUE TITLE
Make _checkpattern(count=50) configureable

### ISSUE THREAD

**Issue by danwos** [pytest-dev/pytest-xprocess#3]
The wait_pattern seems to be checked only for the first 50 lines of process stdout.
This is really not much during test runs, where logs are mostly configured to run on DEBUG level.

The hard coded value count=50 from https://github.com/pytest-dev/pytest-xprocess/blob/master/xprocess.py#L149
should be configurable via a parameter inside the ensure function:

```python
def ensure(self, name, preparefunc, restart=False, count=50):
    ...
    if not callable(wait):
                check = lambda: self._checkpattern(f, wait, count)
            else:
                check = wait
            if check():
                self.log.debug("%s process startup detected", name)
            else:
                raise RuntimeError("Could not start process %s" % name)
```

Beside this, everything works like a charm.

**Comment by jaraco** [comment]
Fixed in #5. Released as 0.12.
