### ISSUE TITLE
Alternative approach to check process state during xprocess.ensure call

### ISSUE THREAD

**Issue by northernSage** [pytest-dev/pytest-xprocess#55]
`XProcess.ensure` currently relies on string matching (`XProcessStarter.pattern`) to check if a process has finished starting. While this works in most situations it starts getting a bit inconvenient when working with processes that don't have too much output or no output at all. We could provide an additional way of checking if processes are ready to answer queries by allowing the user to pass in a callback function to xprocess which will (optionally) be used to assert process responsiveness instead of (or in conjunction with) the pattern matching.

I would be willing to work on a PR if we decide to go ahead with the idea.

**Comment by nicoddemus** [comment]
The idea is interesting... I can imagine a process which doesn't produce output, but writes a few files during startup, which then the custom callback would be able to check. 👍 to the idea from me.

**Comment by northernSage** [comment]
Nice, the PR should be out in the next few days. Also, big thanks to @davidism for the suggestion.
