### ISSUE TITLE
Lack of dedicated documentation page

### ISSUE THREAD

**Issue by northernSage** [pytest-dev/pytest-xprocess#66]
Our `README.rst` is starting to get quite large so I believe it would be nice to start working on dedicated doc pages for `pytest-xprocess` (probably using something like Sphinx). I'll try to get started on this in the next few days. I'm opening the issue for documenting the process and in case anyone has suggestions or want to help.

**Comment by nicoddemus** [comment]
Are you planning on hosting on ReadTheDocs (and I strongly recommend to do so)? If so I suggest to go ahead and create the project right away. 😁 

Please also add me as maintainer there, my user name is also `nicoddemus`. 👍 

To reduce the bus factor I suggest to add @RonnyPfannschmidt too (if Ronny agrees of course). Ronny's username is `RonnyPfannschmidt`.

**Comment by RonnyPfannschmidt** [comment]
Happy to help with config

**Comment by northernSage** [comment]
> Are you planning on hosting on ReadTheDocs (and I strongly recommend to do so)?

I've just imported the project to rtd and added you @nicoddemus and @RonnyPfannschmidt as maintainers. I haven't done any configs yet, though, just created it so we can get started. I really appreciate your help 😄

**Comment by nicoddemus** [comment]
I've made sure the webhook is set: https://github.com/pytest-dev/pytest-xprocess/settings/hooks

From now on if you push docs, readthedocs should build and publish the docs automatically. 👍 

Thanks for tackling this!
