### ISSUE TITLE
Encapsulate xprocess internals info, popen and log handles into single object for resource cleanup

### ISSUE THREAD

**Issue by northernSage** [pytest-dev/pytest-xprocess#67]
Following @RonnyPfannschmidt suggestion in #64, encapsulating the references and objects used for process resource clean-up in `XProcess` seems like a natural follow up to improve the PR and make the code readable and less error-prone when compared to the current approach of separate yet logically/semantically related lists.

**Comment by RonnyPfannschmidt** [comment]
@northernSage as part of the cleanup i recommend turning it into a package and having the pytest_plugin inside the xprocess package as well as _ prefixed modules
this would also prevent issues like #77 by enabling to use find_packages 

a quick usage check sould be done to see if any imports happen from 3rd parties

if noboddy else imports this, then its probably fine to just go ahead and use pytest_xproces as root package name to ensure that detail

**Comment by northernSage** [comment]
I agree. I'll try to get this and other cleanup suggestions ready for our next release 👍🏻

**Comment by northernSage** [comment]
addressed in #85
