### ISSUE TITLE
`tests/server.py` should bind to a random port and report that back to test code

### ISSUE THREAD

**Issue by postmasters** [pytest-dev/pytest-xprocess#72]
**Is your feature request related to a problem? Please describe.**

Currently test code specifies which port the `TestServer` should bind to. This could cause conflict in a busy system.

**Describe the solution you'd like**

Let `TestServer` bind to a random port (e.g. port=0), and print out that port so that the test code can connect to it.

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by northernSage** [comment]
Thanks for the suggestion @postmasters! I have rolled this into #76
