### ISSUE TITLE
_internal.py isn't shipped with the 0.18.0 version installed by PyPi

### ISSUE THREAD

**Issue by ipaleka** [pytest-dev/pytest-xprocess#77]
**Describe the bug**
```
File "/home/ipaleka/dev/venvs/algt/lib/python3.9/site-packages/pytest_xprocess.py", line 4, in <module>
  from _internal import getrootdir
ModuleNotFoundError: No module named '_internal'
```

**To Reproduce**

`$ pip install pytest-xprocess`

`from xprocess import ProcessStarter`

**Expected behavior**
Flawless execution like in 0.17.1.

**Environment (please complete the following information):**
 - OS: Debian Stable (5.10.46-2 (2021-07-20) x86_64 GNU/Linux)
 - Python Version: 3.9.2
 - pytest-xprocess version: 0.18.0

------
A workaround is, well, to just download [that file](https://raw.githubusercontent.com/pytest-dev/pytest-xprocess/master/_internal.py) and place it in the environment's site-packages directory next to pytest_xprocess.py.

**Comment by northernSage** [comment]
Thanks for the quick feedback @ipaleka  , I'll go ahead and prepare a patch release fixing that.

**Comment by ipaleka** [comment]
No problem, I'm glad. Btw, great job with this new 0.18.x version and, of course, with the package itself.

Best regards!
