### ISSUE TITLE
evaluate getting a named dir from the pytest cache

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest-xprocess#8]
instead of putting another dot-dir into the rootdir, we should take a look at asking one form pytest-cache

**Comment by nicoddemus** [comment]
Fine by me. 

I see that `config.cache` does not expose its directory though (`_cachedir` is private).

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus cache does expose a way for plugins to make named folders it correctly knows about, xprocess can use that (`cache.makedir`)

**Comment by nicoddemus** [comment]
I see, thanks!

**Comment by northernSage** [comment]
can I write a PR for this?

**Comment by nicoddemus** [comment]
Sure thing @northernSage, please go ahead!
