### ISSUE TITLE
Published docs out-of-date (v0.18.0 'UNRELEASED'; should be v0.18.1)

### ISSUE THREAD

**Issue by jclerman** [pytest-dev/pytest-xprocess#83]
**Describe the bug**
The published documentation is out-of-date - looks like it's for v0.18.0, but repo and published package at PyPi are at 0.18.1.  Perhaps documentation-build or deployment wasn't done for v0.18.1 when it was published to PyPi?

This isn't really an issue with the source code here, but this seems like the best place to file it.

**To Reproduce**
1. https://pytest-xprocess.readthedocs.io/en/latest/changes.html
2. Note that the latest version is listed as "0.18.0 (UNRELEASED)"

**Expected behavior**
The `CHANGELOG.rst` shown in the latest version of the repo, associated with v0.18.1, should be served at the readthedocs.io site.

**Comment by northernSage** [comment]
Thanks for letting us know @jclerman. The docs were updated for 0.18.1 in #82, but I missed the changelog file. I went ahead and just included `CHANGELOG.rst` into the docs to avoid this problem in the future.
