### ISSUE TITLE
Logs are overwritten for each new process

### ISSUE THREAD

**Issue by varunsh-xilinx** [pytest-dev/pytest-xprocess#91]
**Is your feature request related to a problem? Please describe.**
The log file is overwritten every time a new process is launched, making it difficult to see the process's log for a failed run that occurred in the middle of the test suite.

**Describe the solution you'd like**
I think a better approach would be to delete the log at the start of the pytest session, then append to it throughout the session instead of overwriting it. In addition to the process's log, adding the current test information would be useful too to match the log to the test. It could also be an option to the user to overwrite or append to the log.

**Describe alternatives you've considered**
To see a particular failing test, I've filtered pytest to only run the one test so I can see the process's log.

**Additional context**
N/A

**Comment by northernSage** [comment]
Thanks for the suggestions @varunsh-xilinx. This sounds like a sensible feature to have, following are some tips for anyone feeling like giving this a go:

1. Look into [pytest_sessionstart](https://docs.pytest.org/en/6.2.x/reference.html#pytest.hookspec.pytest_sessionstart) hook for deliting the log files
2. Check [`XProcessInfo.logpath`](https://github.com/pytest-dev/pytest-xprocess/blob/master/xprocess/xprocess.py#L25) and where streams to such files are actually opened, such as in [`stdout = open(str(info.logpath), "wb", 0)`](https://github.com/pytest-dev/pytest-xprocess/blob/master/xprocess/xprocess.py#L232). These are good starting points to play with by opening in append mode and making the necessary adjustments from there.
