### ISSUE TITLE
Crashes when pytest cache is disabled

### ISSUE THREAD

**Issue by levsa** [pytest-dev/pytest-xprocess#92]
**Describe the bug**
xprocess fixture fails to initialize when running pytest with `-p no:cacheprovider`:

```
    @pytest.fixture(scope="session")
    def xprocess(request):
        """yield session-scoped XProcess helper to manage long-running
        processes required for testing."""

>       rootdir = getrootdir(request.config)

../../.pyenv/versions/3.7.9/envs/dev@3.7.9/lib/python3.7/site-packages/pytest_xprocess.py:40:

    def getrootdir(config):
>       return config.cache.makedir(".xprocess")
E       AttributeError: 'Config' object has no attribute 'cache'
```

**To Reproduce**
1. Start tests with `pytest -p no:cacheprovider`

**Expected behavior**
Successful test run

**Environment (please complete the following information):**
 - OS: macOS Big Sur
 - Python Version 3.7.9
 - pytest-xprocess version 0.18.1

**Comment by levsa** [comment]
Thanks for your reply, @northernSage .  The reason for disabling the cache is that we thought we didn’t need it because tests are run by Jenkins and we wanted to avoid needing to configure storage Also, the cache isn’t needed since all tests are run each time. We are using and old version of pytest-xprocess that doesn’t need cache and we wanted to upgrade.

**Comment by northernSage** [comment]
For the time I've been maintaining it,  xprocess has actually always used caching for keeping track of  process logs and PID. The only different is that the said process is now better coupled with pytest's cache plugin as opposed to writing data to separate files on disk as it used to do (I wrote the PR changing it). This seems like a non-issue, so I'll go ahead and close it. 

Thanks for the feedback!
